#!/bin/sh
# postinst script for multiflexi-abraflexi-ipex
set -e

. /usr/share/debconf/confmodule

APPLICATION=$(echo $DPKG_MAINTSCRIPT_PACKAGE | sed 's/multiflexi-//')
for file in $(ls /usr/lib/$APPLICATION/multiflexi/*.app.json)
do
	multiflexi-cli application:import-json --file $file
done

for file in $(ls /usr/lib/$APPLICATION/multiflexi/*.crdprototype.json)
do
        multiflexi-cli credential-prototype:import-json --file $file
done
